# Generated by Django 4.2.7 on 2024-01-01 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Middle", "Middle"),
                            ("Hard", "Hard"),
                        ],
                        max_length=6,
                    ),
                ),
                ("dictionary", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Eazy", "Eazy"),
                            ("Middle", "Middle"),
                            ("Hard", "Hard"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercise.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_to_repeat",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "day_repeat_level",
                    models.CharField(
                        choices=[(1, "1"), (3, "3"), (5, "5"), (7, "7"), (30, "30")],
                        default=1,
                        max_length=6,
                    ),
                ),
                (
                    "native_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="native_word",
                        to="exercise.word",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exercise.word"
                    ),
                ),
            ],
        ),
    ]
