# Generated by Django 3.2.22 on 2024-01-07 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('dictionary', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('false_answer_count', models.IntegerField(default=0)),
                ('true_answer_count', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.language')),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_to_repeat', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('day_repeat_level', models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (7, '7'), (30, '30')], default=1)),
                ('native_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_word', to='exercise.word')),
            ],
        ),
    ]
