# Generated by Django 4.2.7 on 2024-01-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userword",
            name="day_repeat_level",
            field=models.IntegerField(
                choices=[(1, "1"), (3, "3"), (5, "5"), (7, "7"), (30, "30")], default=1
            ),
        ),
    ]
