# Generated by Django 4.2.7 on 2023-12-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="language",
        ),
        migrations.AddField(
            model_name="word",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercise.language",
            ),
            preserve_default=False,
        ),
    ]
