# Generated by Django 3.2.22 on 2024-01-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learn_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish')], max_length=10),
        ),
    ]
