# Generated by Django 3.2.22 on 2024-01-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240106_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learn_language',
            field=models.CharField(choices=[('English', 'English'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('English', 'English'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish')], max_length=10),
        ),
    ]
